import fs from "fs";
import path from "path";
import Link from "next/link";
import { BirdsEyeNavbar } from "@/components/BirdsEyeNavbar";
import { Footer } from "@/components/Footer";
import { CountyExplorer } from "./CountyExplorer";
import { TexasComparisonButton, TexasComparisonProvider } from "./TexasComparison";
import type { County, Snapshot } from "./types";

export const metadata = {
  title: "Lithium in Drinking Water & Obesity | The Metascience Observatory",
  description: "Explore county-level correlations between lithium in US drinking water and adult obesity, with national and state scatterplots, source comparisons, and downloadable data.",
};

const DOWNLOAD = "/data/lithium-drinking-water";
const linkStyle = "underline underline-offset-4 hover:text-primary focus-visible:outline focus-visible:outline-2";
const format = (n: number) => n.toFixed(3);

export default function LithiumDrinkingWaterPage() {
  const snapshot = JSON.parse(fs.readFileSync(path.join(process.cwd(), "data/birds_eye_reviews/lithium_drinking_water/snapshot.v1.json"), "utf8")) as Snapshot;
  const exposures = snapshot.exposures.filter(exposure => exposure.column !== "log10_usgs_all");
  // Keep the full export on the server and pass only the explorer's fields.
  const columns = new Set(["fips", "countyname", "state", "totalpopulation", "obesity_adjprev"]);
  for (const exposure of exposures) {
    for (const column of [exposure.column, exposure.raw, exposure.count]) columns.add(column);
  }
  const counties = snapshot.counties.map(row => Object.fromEntries([...columns].map(column => [column, row[column]])) as County);
  const national = snapshot.results.correlations_main.find(row => row.column === "ucmr5_all_li_detfrac")!;
  const texas = snapshot.results.texas_obesity.find(row => row.column === "ucmr5_all_li_detfrac")!;

  return <>
    <BirdsEyeNavbar />
    <main className="mx-auto min-h-screen w-full max-w-[1600px] px-4 pb-16 pt-24 sm:px-8 lg:px-16">
      <Link href="/birds-eye-reviews/lithium-weight-gain" className={`text-sm text-muted-foreground ${linkStyle}`}>&larr; Lithium &amp; weight gain: clinical studies</Link>
      <h1 className="mt-2 font-clarendon text-3xl font-bold sm:text-4xl">
        Lithium in drinking water &amp; obesity{" "}
        <span className="align-middle font-sans text-base font-semibold text-red-800 sm:text-lg">
          (Page generated by GPT-6 Astra, minimal human review)
        </span>
      </h1>
      <p className="mt-3 max-w-3xl text-sm leading-relaxed text-muted-foreground">Do counties with more lithium in their water have higher obesity rates? Explore six lithium measures across three water datasets. Each point represents one county; the outcome is a modeled, age-adjusted estimate of adult obesity prevalence in that county. The state filter selects counties rather than aggregating them into state averages.</p>

      <section aria-label="Saved headline findings" className="my-6 grid gap-3 md:grid-cols-2">
        <div className="rounded-lg border border-border bg-muted/30 p-4">
          <p className="text-sm font-semibold">National · saved primary result</p>
          <p className="mt-1 text-2xl font-semibold tabular-nums">ρ = {format(national.spearman as number)} <span className="text-sm font-normal text-muted-foreground">· {(national.n as number).toLocaleString("en-US")} counties</span></p>
          <p className="mt-1 text-xs leading-relaxed text-muted-foreground">95% CI {format(national.spearman_lo as number)} to {format(national.spearman_hi as number)} · 2,000 state-cluster bootstrap resamples.</p>
          <p className="mt-1 text-xs leading-relaxed text-muted-foreground">Using UCMR5 detection fraction and equal county weights.</p>
        </div>
        <div className="rounded-lg border border-border bg-muted/30 p-4">
          <p className="text-sm font-semibold">Texas · saved primary result</p>
          <p className="mt-1 text-2xl font-semibold tabular-nums">ρ = {format(texas.spearman as number)} <span className="text-sm font-normal text-muted-foreground">· {String(texas.n)} counties</span></p>
          <p className="mt-1 text-xs leading-relaxed text-muted-foreground">Using UCMR5 detection fraction and equal county weights.</p>
        </div>
      </section>

      <TexasComparisonProvider>
      <CountyExplorer counties={counties} exposures={exposures} />

      <section className="mt-10 border-t border-border pt-8" aria-labelledby="interpretation-heading">
        <h2 id="interpretation-heading" className="font-clarendon text-2xl font-bold">What can this comparison tell us? <span className="font-sans text-sm font-normal text-red-800">(AI generated by APT-6 Astra)</span></h2>
        <div className="mt-4 grid gap-6 text-sm leading-relaxed md:grid-cols-2">
          <div>
            <h3 className="font-semibold">A geographic association is not an individual effect</h3>
            <p className="mt-2 text-muted-foreground">County averages do not measure an individual&apos;s lithium intake. Water systems cross county boundaries, monitoring is uneven, and obesity estimates are modeled. Demographics, income, climate, and other factors may explain part of a geographic pattern. These scatterplots show unadjusted associations.</p>
            <h3 className="mt-4 font-semibold">The national result depends on the measure</h3>
            <p className="mt-2 text-muted-foreground">The primary rank correlation is close to zero nationally and positive within Texas. Some other measures and adjusted models have intervals that exclude zero. The modeled geometric mean also has a sample-count artifact, so it requires particular care. Saved obesity regressions use HC3 robust errors, without clustering by state.</p>
            <p className="mt-3 flex flex-wrap gap-x-4 gap-y-2"><a href={`${DOWNLOAD}/correlations_main.csv`} download className={linkStyle}>National results CSV</a><a href={`${DOWNLOAD}/texas_obesity.csv`} download className={linkStyle}>Texas results CSV</a><a href={`${DOWNLOAD}/ols_ladders.csv`} download className={linkStyle}>Adjusted models CSV</a></p>
          </div>
          <div>
            <h3 className="font-semibold">How this relates to Slime Mold Time Mold</h3>
            <p className="mt-2 text-muted-foreground">Their <a href="https://slimemoldtimemold.com/2021/11/08/a-chemical-hunger-interlude-i-the-fattest-cities-in-the-land/" className={linkStyle}>2021 city comparison</a> discussed McAllen and San Antonio, using regional aquifer measurements as exposure proxies. This analysis compares counties with a consistent health-outcome definition and includes EPA finished-water measurements. Dates and geographic units differ; this is not an exact replication.</p>
            <TexasComparisonButton />
            <p className="mt-2 text-muted-foreground">Hidalgo covers the McAllen area; Bexar is San Antonio&apos;s central county. The button selects Texas, highlights both counties, and clears coverage minimums. Use Reset to return to all states plus DC. A central county is not necessarily the full metropolitan area.</p>
          </div>
        </div>
      </section>

      </TexasComparisonProvider>

      <section className="mt-8 rounded-lg border border-border p-5" aria-labelledby="methods-heading">
        <h2 id="methods-heading" className="font-clarendon text-xl font-bold">Data and methods</h2>
        <div className="mt-4 grid gap-5 text-sm leading-relaxed md:grid-cols-2">
          <p><strong>Detection limits.</strong> About 72% of UCMR5 results are below 9 µg/L. Detection fraction is the proportion at or above this limit. Medians substitute 4.5 µg/L for nondetects. A zero detection fraction does not mean zero lithium. Modeled geometric means depend on sample count when every sample is a nondetect.</p>
          <p><strong>Missing outcomes.</strong> All 120 Kentucky and 67 Pennsylvania counties lack health outcomes in this snapshot. They remain in downloads for the selected geography, but contribute no complete pairs. Connecticut planning-region counts are estimates from an area crosswalk and can be fractional.</p>
          <p><strong>Correlations.</strong> Spearman uses average ranks for tied values. Population weighting applies a weighted Pearson correlation to those ranks. Pearson uses the selected exposure, with log₁₀ concentrations where labeled. At least three complete pairs with positive population and variation in both variables are required. Filtered correlations have no confidence interval or p-value.</p>
          <p><strong>Snapshot.</strong> This page uses the existing analysis export. Measurement periods vary by source. Exported {new Date(snapshot.exportedAt).toISOString().slice(0, 19).replace("T", " ") + " UTC"} (export time, not sampling date). Fingerprint: <code className="break-all">{snapshot.fingerprint.slice(0, 16)}</code>.</p>
        </div>
        <details className="mt-5">
          <summary className="cursor-pointer font-semibold">Source provenance and downloads</summary>
          <ul className="mt-4 space-y-3 text-sm">{snapshot.sources.map(source => <li key={source.name}><a href={source.url} className={linkStyle}>{source.name}</a> <span className="text-muted-foreground">· {source.period}</span><p className="mt-1 text-muted-foreground">{source.description}</p></li>)}</ul>
          <div className="mt-5 flex flex-wrap gap-4 text-sm"><a href={`${DOWNLOAD}/merged_county.csv`} download className={linkStyle}>Full county CSV (51 columns)</a><a href={`${DOWNLOAD}/variables.csv`} download className={linkStyle}>Variable dictionary CSV</a><a href={`${DOWNLOAD}/provenance.json`} download className={linkStyle}>Snapshot provenance (SHA-256)</a></div>
        </details>
      </section>
    </main>
    <Footer />
  </>;
}
